### PR TITLE
Setup TravisCI

### LINKED ISSUE #140: Set up the repo for Travis to run tests.
The repository is already linked to Travis for open source. 

We would like for someone to help with setting up the yaml files for Travis to test the repo against
Python 2.7 and 3.6.x
Django 1.11.1
Tox
Flake8 test
lintjs
scss lint

### PR DESCRIPTION
**Pull request by NdagiStanley**
#### What does this PR do?
Fixes #140 
#### Description of Task to be completed?
Setup `.travis.yml` to test the repo against:

- [x] Python 2.7 and 3.6.x
- [x] Django 1.11.1 (Tested under tox)
- [x] Tox
- [x] ~Flake8 test~ pep8 now called pycodestyle
- [x] ~lintjs~ eslint
- [x] ~scss lint~ stylelint

pep8 is deprecated
flake8 had issues running

#### How should this be manually tested?
Restart a build on travis or have a look at this [one](url)
#### Any background context you want to provide?
This is still WIP bearing in mind the number of considerations to be made.
The codebase does require a lot of editing to fix the linting errors.
There is an error in Django that I may need to look into a bit more: `SECRET_KEY not found` yet we have it in line 10 of the `src/settings.py`
#### Questions:
scss lint was mentioned yet I did not find any `.scss` files. Are you planning to move to `SASS`?

### CODE REVIEW

**Comment by tawanike** [comment]
@NdagiStanley Thanks for looking at this. The we need to move from the current version of Django 1.6.5 to a Django 1.1.11. The changes on this PR are mainly to put in place a better and easier way manage the development of the project going forward, enforcing best practices and improving the code quality. 

The bigger goal is for us to build a project that can be adopted by other accelerators across Africa. Your contributions would be very much appreciated as this will enable us to bring together different minds different skill and help JoziHub and other accelerators quickly and easily build a web presence.

**Comment by NdagiStanley** [comment]
Awesome. Let's do this.

**Comment by NdagiStanley** [comment]
Could we start by fixing the `SECRET_KEY not found yet we have it in line 10 of the src/settings.py`?

**Comment by tawanike** [comment]
To deal with the SECRET_KEY issue try to create a settings_local.py file and add the SECRET_KEY constant and a string value there. It should resolve the issue.

**Pull request closed without merging**
